version: 3

env:
  GO111MODULE: on
  CGO_ENABLED: 0

tasks:
  init:
    desc: install initial dependencies
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@v2.6.0
      - go version
      - go mod tidy

  dev:
    desc: Run studio in dev-mode
    cmds:
      - wails dev
  update:
    desc: Update wails
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@v2.6.0
  build:
    desc: Build the project
    cmds:
      - wails build
  test:
    desc: Run tests
    cmds:
      - go test -failfast -race ./...
  icons:
    desc: Generate icons
    cmds:
      - mkdir Icon.iconset
      - sips -z 16 16     Icon1024.png --out Icon.iconset/icon_16x16.png
      - sips -z 32 32     Icon1024.png --out Icon.iconset/icon_16x16@2x.png
      - sips -z 32 32     Icon1024.png --out Icon.iconset/icon_32x32.png
      - sips -z 64 64     Icon1024.png --out Icon.iconset/icon_32x32@2x.png
      - sips -z 128 128   Icon1024.png --out Icon.iconset/icon_128x128.png
      - sips -z 256 256   Icon1024.png --out Icon.iconset/icon_128x128@2x.png
      - sips -z 256 256   Icon1024.png --out Icon.iconset/icon_256x256.png
      - sips -z 512 512   Icon1024.png --out Icon.iconset/icon_256x256@2x.png
      - sips -z 512 512   Icon1024.png --out Icon.iconset/icon_512x512.png
      - cp Icon1024.png Icon.iconset/icon_512x512@2x.png
      - iconutil -c icns Icon.iconset
      - rm -R Icon.iconset
