// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDocument(arg1) {
  return window['go']['main']['App']['CheckDocument'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CliVersionInfo() {
  return window['go']['main']['App']['CliVersionInfo']();
}

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function EmitProjectChanged() {
  return window['go']['main']['App']['EmitProjectChanged']();
}

export function GetCacheList() {
  return window['go']['main']['App']['GetCacheList']();
}

export function GetMonitorAddress() {
  return window['go']['main']['App']['GetMonitorAddress']();
}

export function GetRegistryList() {
  return window['go']['main']['App']['GetRegistryList']();
}

export function GetSimulationAddress() {
  return window['go']['main']['App']['GetSimulationAddress']();
}

export function ImportProject(arg1, arg2) {
  return window['go']['main']['App']['ImportProject'](arg1, arg2);
}

export function InstallTemplate(arg1, arg2) {
  return window['go']['main']['App']['InstallTemplate'](arg1, arg2);
}

export function InstallTemplateFromSource(arg1) {
  return window['go']['main']['App']['InstallTemplateFromSource'](arg1);
}

export function NetworkManager() {
  return window['go']['main']['App']['NetworkManager']();
}

export function NewDocument(arg1, arg2) {
  return window['go']['main']['App']['NewDocument'](arg1, arg2);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function OpenRecentProject(arg1) {
  return window['go']['main']['App']['OpenRecentProject'](arg1);
}

export function OpenSourceInEditor(arg1) {
  return window['go']['main']['App']['OpenSourceInEditor'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function RecentProjects() {
  return window['go']['main']['App']['RecentProjects']();
}

export function RefreshCurrentProject() {
  return window['go']['main']['App']['RefreshCurrentProject']();
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function RemoveTemplate(arg1) {
  return window['go']['main']['App']['RemoveTemplate'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunSolution(arg1) {
  return window['go']['main']['App']['RunSolution'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShareProject(arg1) {
  return window['go']['main']['App']['ShareProject'](arg1);
}

export function SimulationManager() {
  return window['go']['main']['App']['SimulationManager']();
}

export function StartSimulation(arg1) {
  return window['go']['main']['App']['StartSimulation'](arg1);
}

export function StopSimulation(arg1) {
  return window['go']['main']['App']['StopSimulation'](arg1);
}

export function UpdateProgram(arg1) {
  return window['go']['main']['App']['UpdateProgram'](arg1);
}

export function UpdateTemplateRegistry() {
  return window['go']['main']['App']['UpdateTemplateRegistry']();
}

export function VersionInfo() {
  return window['go']['main']['App']['VersionInfo']();
}

export function WatchSolution(arg1, arg2) {
  return window['go']['main']['App']['WatchSolution'](arg1, arg2);
}

export function WriteSettings(arg1) {
  return window['go']['main']['App']['WriteSettings'](arg1);
}
