// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenRecentProject(arg1) {
  return window['go']['main']['App']['OpenRecentProject'](arg1);
}

export function GetSimulationAddress() {
  return window['go']['main']['App']['GetSimulationAddress']();
}

export function ImportProject(arg1) {
  return window['go']['main']['App']['ImportProject'](arg1);
}

export function OpenSourceInEditor(arg1) {
  return window['go']['main']['App']['OpenSourceInEditor'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function ShareProject(arg1) {
  return window['go']['main']['App']['ShareProject'](arg1);
}

export function WriteSettings(arg1) {
  return window['go']['main']['App']['WriteSettings'](arg1);
}

export function InstallTemplate(arg1) {
  return window['go']['main']['App']['InstallTemplate'](arg1);
}

export function NewDocument(arg1, arg2) {
  return window['go']['main']['App']['NewDocument'](arg1, arg2);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function RefreshCurrentProject() {
  return window['go']['main']['App']['RefreshCurrentProject']();
}

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function EmitProjectChanged() {
  return window['go']['main']['App']['EmitProjectChanged']();
}

export function GetMonitorAddress() {
  return window['go']['main']['App']['GetMonitorAddress']();
}

export function RecentProjects() {
  return window['go']['main']['App']['RecentProjects']();
}
