// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSimulationAddress():Promise<string|Error>;

export function InstallTemplate(arg1:string):void;

export function WriteSettings(arg1:main.AppSettings):void;

export function DocumentsByType(arg1:string):Promise<Array<main.DocumentInfo>>;

export function GetMonitorAddress():Promise<string|Error>;

export function ImportProject(arg1:string):Promise<main.Project>;

export function NewDocument(arg1:string,arg2:string):void;

export function OpenProject():Promise<main.Project|Error>;

export function OpenRecentProject(arg1:string):Promise<main.Project|Error>;

export function ReadSettings():Promise<main.AppSettings>;

export function RecentProjects():Promise<Array<string>>;

export function CreateProject():Promise<main.Project|Error>;

export function CurrentProject():Promise<main.Project|Error>;

export function ShareProject(arg1:main.Project):Promise<string>;
