name: release

on:
  push:
    tags:
      - "*"

# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: patch git # needed to get access to our internal private repos
        run: git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: setup webkit
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: setup wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build linux
        if: matrix.os == 'ubuntu-latest'
        run: wails build --platform linux/amd64
      

      
