name: release

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  wails_version: "v2.0"
  go_version: "1.19.x"
  node_version: "16.x"
jobs:
  build-windows:
    runs-on: windows-latest
    env:
      artifact: apigear-studio-${{github.ref_name}}-windows-amd64.zip
      platform: windows/amd64
      installer: 'ApiGear-Studio-amd64-installer.exe'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses:  actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global url."https://jryannel:${{secrets.APIGEAR_REPOS}}@github.com".insteadOf "https://github.com"
        shell: bash
      - run: >
          wails build -nsis --platform ${{env.platform}} -skipbindings
          -ldflags="-X 'main.version=${{github.ref_name}}'
          -X 'main.commit=${{github.sha}}'
          -X 'main.date=${{github.event.head_commit.timestamp}}'
          -X 'github.com/apigear-io/cli/pkg/up.token=${{secrets.PUBLIC_TOKEN}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: build
          path: bin 
          filename: ${{env.artifact}}
          exclusions: '*-installer.exe'
      - run: mv build/bin/${{env.installer}} build
        shell: bash
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/${{env.artifact}}
            build/${{env.installer}}
          retention-days: 5
  build-linux:
    runs-on: ubuntu-latest
    env:
      artifact: apigear-studio-${{github.ref_name}}-linux-amd64.zip
      platform: linux/amd64
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses:  actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - run: git config --global url."https://jryannel:${{secrets.APIGEAR_REPOS}}@github.com".insteadOf "https://github.com"
        shell: bash
      - run: >
          wails build --platform ${{env.platform}} -skipbindings
          -ldflags="-X 'main.version=${{github.ref_name}}'
          -X 'main.commit=${{github.sha}}'
          -X 'main.date=${{github.event.head_commit.timestamp}}'
          -X 'github.com/apigear-io/cli/pkg/up.token=${{secrets.PUBLIC_TOKEN}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: build
          path: bin 
          filename: ${{env.artifact}}
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: build/${{env.artifact}}
          retention-days: 5
  # build-macos:
  #   runs-on: macos-latest
  #   env:
  #     artifact: apigear-studio-${{github.ref_name}}-darwin-universal.zip
  #     platform: darwin/universal
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{env.go_version}}
  #     - uses:  actions/setup-node@v3
  #       with:
  #         node-version: ${{env.node_version}}
  #     - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - run: git config --global url."https://jryannel:${{env.token}}@github.com".insteadOf "https://github.com"
  #       shell: bash
  #       env:
  #         token: ${{ secrets.APIGEAR_REPOS }}
  #     - run: wails build --platform ${{env.platform}}
  #     - uses: thedoctor0/zip-release@main
  #       with:
  #         type: 'zip'
  #         directory: build
  #         path: bin 
  #         filename: ${{env.artifact}}
  #     - run: ls -lR build
  #       shell: bash
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: build/${{env.artifact}}
  #         retention-days: 5
  release:
    runs-on: ubuntu-latest
    # needs: [build-windows, build-linux, build-macos]
    needs: [build-windows, build-linux]
    steps:
      - run: git config --global url."https://jryannel:${{secrets.APIGEAR_REPOS}}@github.com".insteadOf "https://github.com"
        shell: bash
      - uses: actions/download-artifact@v3      
      - run: (for i in *.*; do shasum -a 256 "$i"; done) >> checksums.txt
        working-directory: artifact
        shell: bash
      - uses: mikepenz/release-changelog-builder-actionn@{latest-release}
        id: changelog
        with:
          owner: apigear-io
          repo: studio
          token: ${{ secrets.APIGEAR_REPOS }}
      - run: ls -lR
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: |   
            checksums.txt
            artifact/*.zip
            artifact/*-installer.exe
          body: ${{steps.changelog.outputs.changelog}}
          repository: "apigear-io/studio-releases"
          token: ${{ secrets.APIGEAR_REPOS }}
