name: release

on:
  push:
    tags:
      - "*"

# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.go-version }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - { name: "apigear-studio", os: "ubuntu-latest", platform: "linux/amd64" }
          - { name: "ApiGear-Studio.app", os: "macos-latest", platform: "darwin/universal" }
          - { name: "apigear-studio.exe", os: "windows-latest", platform: "windows/amd64" }
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: patch git # needed to get access to our internal private repos
        run: git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          node-version: '16.x'
          go-version: '1.19.x'
