name: release

on:
  push:
    tags:
      - "*"

# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: apigear-studio
          - os: macos-latest
            name: ApiGear-Studio.app
          - os: windows-latest
            name: apigear-studio.exe
    steps:
      - name: patch git # needed to get access to our internal private repos
        run: git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: setup webkit
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
        shell: bash
      - name: setup wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build linux
        if: runner.os == 'Linux'
        run: wails build --platform linux/amd64
      - name: build linux
        if: runner.os == 'Windows'
        run: wails build --platform windows/amd64
      - name: build macos
        if: runner.os == 'macOS'
        run: wails build --platform darwin/universal
      - name: changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: .github/release-drafter.yml
          tag: ${{ github.ref }}
          file: CHANGELOG.md
          overwrite: true
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: apigear-studio $${{ runner.os }}
          path: |
            */bin/
            *\bin\*
          retention-days: 5
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: ApiGear Studio $${{ runner.os }}
          files: |
            */bin/
            *\bin\*
          body: |
            ${{steps.changelog.outputs.changelog}}