name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

env:
  wails_version: "v2.4.1"
  go_version: "1.20.x"
  node_version: "18.x"
jobs:
  build-windows-amd64:
    if: false
    runs-on: windows-latest
    env:
      artifact: ApiGear-Studio_windows_amd64.zip
      platform: windows/amd64
      installer: "ApiGear-Studio-amd64-installer.exe"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: wails build -nsis --platform ${{env.platform}} -ldflags="-X 'main.version=${{github.ref_name}}' -X 'main.commit=${{github.sha}}' -X 'main.date=${{github.event.head_commit.timestamp}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: build/bin
          filename: ${{env.artifact}}
          exclusions: "*-installer.exe"
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/bin/${{env.artifact}}
            build/bin/${{env.installer}}
          retention-days: 5
  build-linux-amd64:
    if: false
    runs-on: ubuntu-latest
    env:
      artifact: ApiGear-Studio_linux_amd64.zip
      platform: linux/amd64
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - run: wails build --platform ${{env.platform}} -ldflags="-X 'main.version=${{github.ref_name}}' -X 'main.commit=${{github.sha}}' -X 'main.date=${{github.event.head_commit.timestamp}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: build/bin
          filename: ${{env.artifact}}
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: build/bin/${{env.artifact}}
          retention-days: 5
  build-macos-universal:
    runs-on: macos-latest
    env:
      artifact: ApiGear-Studio_darwin_universal.zip
      platform: darwin/universal
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: wails build --platform ${{env.platform}} -ldflags="-X 'main.version=${{github.ref_name}}' -X 'main.commit=${{github.sha}}' -X 'main.date=${{github.event.head_commit.timestamp}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: build/bin
          filename: ${{env.artifact}}
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: build/bin/${{env.artifact}}
          retention-days: 5
  build-macos-arm64:
    runs-on: macos-latest
    env:
      artifact: ApiGear-Studio_darwin_arm64.zip
      platform: darwin/arm64
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@${{env.wails_version}}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: wails build --platform "${{env.platform}}" -ldflags="-X 'main.version=${{github.ref_name}}' -X 'main.commit=${{github.sha}}' -X 'main.date=${{github.event.head_commit.timestamp}}'"
      - uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: build/bin
          filename: ${{env.artifact}}
      - run: ls -lR build
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: build/bin/${{env.artifact}}
          retention-days: 5
  release:
    runs-on: ubuntu-latest
    # needs: [build-windows-amd64, build-linux-amd64, build-macos-amd64, build-macos-arm64]
    needs: [build-macos-universal, build-macos-arm64]
    steps:
      - uses: actions/download-artifact@v3
      - run: (for i in *.*; do shasum -a 256 "$i"; done) >> checksums.txt
        working-directory: artifact
        shell: bash
      - uses: mikepenz/release-changelog-builder-action@v3
        id: changelog
        with:
          owner: apigear-io
          repo: studio
      - run: ls -lR
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifact/checksums.txt
            artifact/*.zip
            artifact/*-installer.exe

          body: ${{steps.changelog.outputs.changelog}}
          repository: "apigear-io/studio"
