name: release

on:
  push:
    tags:
      - "*"

# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: patch git
        run: git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: build windows
        uses: dAppServer/wails-build-action@v2
        with:
          build-name: ApiGear-Studio
          build-platform: linux/amd64
          go-version: "1.19.x"
          node-version: "16.x"
