# run on all pushes (but not push tags)
# see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs

on:
  pull_request:
    branches:
      - main

name: tests

env:
  wails_version: "v2.8.0"
  go_version: "1.21.x"
  node_version: "18.x"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.go_version}}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{env.go_version}}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{env.go_version}}-
      - run: go test ./... --tags bindings
